name: Python checks

on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:
    branches:
      - main
      - 'release-*'

jobs:
  typos:
    name: Typos
    runs-on: ubuntu-latest

    steps:
    - name: Check out MNI 7T BIDS converter
      uses: actions/checkout@v4

    - name: Install MNI 7T BIDS converter
      uses: ./.github/actions/install-project

    - name: Run Typos
      run: typos

  ruff:
    name: Lints
    runs-on: ubuntu-latest

    steps:
    - name: Check out MNI 7T BIDS converter
      uses: actions/checkout@v4

    - name: Install MNI 7T BIDS converter
      uses: ./.github/actions/install-project

    - name: Run Ruff
      run: ruff check --output-format=github

  pyright:
    name: Type checks
    runs-on: ubuntu-latest

    steps:
    - name: Check out MNI 7T BIDS converter
      uses: actions/checkout@v4

    - name: Install MNI 7T BIDS converter
      uses: ./.github/actions/install-project

    - name: Run Pyright
      run: pyright
