name: Release

on:
  push:
    branches:
    - main

permissions:
  contents: write
  packages: write

jobs:
  release-executable:
    name: Release executable
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the compilation Docker image
      run: |
        docker build -t compile_mni_7t_dicom_to_bids -f compile.Dockerfile .

    - name: Build executable
      run: |
        mkdir dist
        docker run --mount type=bind,src=$(pwd)/dist,dst=/mni_7t_dicom_to_bids/dist compile_mni_7t_dicom_to_bids

    - name: Delete old latest release
      run: |
        gh release delete latest --yes || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create latest release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: "Latest development build"
        body: |
          **Automated development build**

          - **Commit:** ${{ github.sha }}
          - **Date:** ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: true
        generate_release_notes: false
        files: dist/mni7t_dcm2bids

  release-image:
    name: Release image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Inventory Image
        run: |
          docker build . --tag ghcr.io/bic-mni/mni-7t-dicom-to-bids:latest
          docker push ghcr.io/bic-mni/mni-7t-dicom-to-bids:latest
